# Generated by Django 3.0.1 on 2020-01-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_sidebaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_solved_problems',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, to='judge.Organization'),
        ),
    ]
