# Generated by Django 3.0.1 on 2020-01-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_auto_20200104_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description_file',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='manifest_file',
        ),
        migrations.AddField(
            model_name='problem',
            name='manifest',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
