# Generated by Django 3.0.1 on 2020-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0012_auto_20200118_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionbatchresult',
            name='memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionbatchresult',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontestcaseresult',
            name='memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissiontestcaseresult',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
