# Generated by Django 3.0.1 on 2020-02-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_auto_20200214_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_problems_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
