# Generated by Django 3.0.3 on 2020-03-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0017_auto_20200307_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
