# Generated by Django 3.0.3 on 2020-03-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0018_auto_20200307_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_modified_date',
            new_name='last_modified',
        ),
    ]
