# Generated by Django 3.0.3 on 2020-03-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0019_auto_20200307_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='post', unique=True),
            preserve_default=False,
        ),
    ]
