# Generated by Django 3.0.4 on 2020-04-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0021_auto_20200326_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('py3', 'Python3'), ('java8', 'Java 8'), ('c++17', 'C++17'), ('haskell', 'Haskell')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_language',
            field=models.CharField(choices=[('py3', 'Python3'), ('java8', 'Java 8'), ('c++17', 'C++17'), ('haskell', 'Haskell')], default='py3', max_length=10),
        ),
    ]
