# Generated by Django 3.0.8 on 2020-07-13 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0025_auto_20200709_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='creator',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='organization',
            name='access_code',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='organization',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='org_short_name', max_length=24),
            preserve_default=False,
        ),
    ]
