# Generated by Django 3.0.8 on 2020-07-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0026_auto_20200713_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', related_query_name='member', to='judge.Organization'),
        ),
    ]
