# Generated by Django 3.0.8 on 2020-08-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0028_organizationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrequest',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=1),
        ),
    ]
